services:
  fpm:
    build: .
    volumes:
      - ./src:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - nginx
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=example
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
