services:
  fpm:
    build: .
    container_name: webapp
    volumes:
      - ./src:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
    env_file:
      - ./.env.development
    environment:
      - ENVIRONMENT=development
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - nginx
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: webserver
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - app-network

  db:
    image: postgres:latest
    restart: unless-stopped
    tty: true
    ports:
      - 5432:5432
    env_file:
      - ./.env.development
    environment:
      - ENVIRONMENT=development
    container_name: database # You .env file should use the same name, i.e POSTGRES_CONTAINER=database
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
