services:
  php-fpm:
    container_name: php-fpm
    build:
      context: . # Path to your PHP-FPM Dockerfile
    volumes:
      - ./src:/var/www/html # Mount your application files into the container
    networks:
      - app-network
    depends_on:
      - db
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=php-docker"
    expose:
      - 9000
    ports:
      - 9000:9000  # PHP-FPM exposed for Nginx

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=example
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
